export const portfolioContent = {
  brand: "NS",
  name: "Nugrah Salam Harahap",
  professionalName: "Nugrah Salam",
  role: "Fullstack Developer & AI Engineer",
  location: "Batam, Indonesia",
  experience: "4 years",
  email: "ompekp@gmail.com",
  whatsapp: "https://wa.me/6287748597957",
  domain: "nugrah.becoder.xyz",
  availability: { label: "Available for projects", detail: "Batam · Indonesia" },
  navigation: [
    { label: "About", href: "#about" },
    { label: "Services", href: "#services" },
    { label: "Works", href: "#works" },
    { label: "Contact", href: "#contact" },
  ],
  eyebrow: "Fullstack Developer · AI Engineer",
  headline: ["Fullstack systems,", "AI workflows,", "built to ship."],
  description: "I build reliable web products, AI integrations, crypto experiences, and n8n automations from interface to infrastructure.",
  proof: "Four years turning product ideas into usable software—combining thoughtful interfaces, dependable backends, and practical automation.",
  metric: { label: "Projects completed", value: "15", suffix: "+" },
  technologies: ["TypeScript", "JavaScript", "Python", "PHP"],
  social: {
    github: "https://github.com/envexx",
    linkedin: "https://www.linkedin.com/in/nugrah-salam-16a408257/",
    instagram: "https://instagram.com/nugrah_hrp",
    x: "https://x.com/mimpowo",
  },
} as const;
